// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SabalanMedical.Infrastracture.Migrations
{
    [DbContext(typeof(SabalanDbContext))]
    partial class SabalanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductNameEn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductNameFr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isHotSale")
                        .HasColumnType("bit");

                    b.Property<bool>("isManufactured")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b21aef73-8ded-4cc3-9aad-adfbd150bed5"),
                            ProductNameEn = "bvf",
                            ProductNameFr = "فیلتر آنتی باکتریال",
                            ProductUrl = "bvf",
                            TypeId = new Guid("65d34326-ce95-474e-96f7-850a6154fefb"),
                            isHotSale = true,
                            isManufactured = true
                        },
                        new
                        {
                            Id = new Guid("398b7e58-bbc3-456f-924e-074c264c4031"),
                            ProductNameEn = "hmef",
                            ProductNameFr = "فیلتر HME",
                            ProductUrl = "HMEF",
                            TypeId = new Guid("65d34326-ce95-474e-96f7-850a6154fefb"),
                            isHotSale = true,
                            isManufactured = true
                        },
                        new
                        {
                            Id = new Guid("b380acf2-45d4-40cc-8413-2b0c38666e3b"),
                            ProductNameEn = "Circular stapler",
                            ProductNameFr = "استپلر حلقوی",
                            ProductUrl = "Circular-stapler",
                            TypeId = new Guid("15f8dfc3-5c88-4a9e-be20-3ac476192583"),
                            isHotSale = true,
                            isManufactured = false
                        },
                        new
                        {
                            Id = new Guid("fd955430-0230-4f1d-92f5-bcaded597262"),
                            ProductNameEn = "Curved stapler",
                            ProductNameFr = "استپلر منحنی برشی",
                            ProductUrl = "Curved-stapler",
                            TypeId = new Guid("15f8dfc3-5c88-4a9e-be20-3ac476192583"),
                            isHotSale = true,
                            isManufactured = false
                        },
                        new
                        {
                            Id = new Guid("c4821c34-c92c-4a0f-a94b-bfd4ad6cfd8b"),
                            ProductNameEn = "Endo bag",
                            ProductNameFr = "اندوبگ",
                            ProductUrl = "Endo-bag",
                            TypeId = new Guid("15f8dfc3-5c88-4a9e-be20-3ac476192583"),
                            isHotSale = false,
                            isManufactured = false
                        },
                        new
                        {
                            Id = new Guid("e88c63c0-b56f-4749-95c9-b6f081cf667c"),
                            ProductNameEn = "Endo GI realod",
                            ProductNameFr = "کارتریج اندوجی",
                            ProductUrl = "Endo-GI-realod",
                            TypeId = new Guid("15f8dfc3-5c88-4a9e-be20-3ac476192583"),
                            isHotSale = false,
                            isManufactured = false
                        },
                        new
                        {
                            Id = new Guid("58c1f884-560a-4433-8467-6df7d7779aa8"),
                            ProductNameEn = "Endo GI stapler",
                            ProductNameFr = "استپلر اندوجی",
                            ProductUrl = "Endo-GI-stapler",
                            TypeId = new Guid("15f8dfc3-5c88-4a9e-be20-3ac476192583"),
                            isHotSale = true,
                            isManufactured = false
                        },
                        new
                        {
                            Id = new Guid("fc72c813-10b4-42f6-a828-9e2b4c6723e4"),
                            ProductNameEn = "Eschelon realod",
                            ProductNameFr = "کارتریج اشلون",
                            ProductUrl = "Eschelon-realod",
                            TypeId = new Guid("15f8dfc3-5c88-4a9e-be20-3ac476192583"),
                            isHotSale = true,
                            isManufactured = false
                        },
                        new
                        {
                            Id = new Guid("6488e50c-b8a0-4af8-9d65-71366156b106"),
                            ProductNameEn = "Eschelon stapler",
                            ProductNameFr = "استپلر اشلون",
                            ProductUrl = "Eschelon-stapler",
                            TypeId = new Guid("15f8dfc3-5c88-4a9e-be20-3ac476192583"),
                            isHotSale = true,
                            isManufactured = false
                        },
                        new
                        {
                            Id = new Guid("59ec2c5b-e639-40da-b7b8-95a6d31f2d6d"),
                            ProductNameEn = "Hemolock clips",
                            ProductNameFr = "کلیپس همولوگ",
                            ProductUrl = "Hemolock-clips",
                            TypeId = new Guid("15f8dfc3-5c88-4a9e-be20-3ac476192583"),
                            isHotSale = false,
                            isManufactured = false
                        },
                        new
                        {
                            Id = new Guid("dd713b1e-379b-43d3-a59e-571c6230ff86"),
                            ProductNameEn = "Ligasure laparascopic",
                            ProductNameFr = "لیگاشور",
                            ProductUrl = "Ligasure-laparascopic",
                            TypeId = new Guid("15f8dfc3-5c88-4a9e-be20-3ac476192583"),
                            isHotSale = false,
                            isManufactured = false
                        },
                        new
                        {
                            Id = new Guid("106f346e-b5e9-4117-b6e1-eb0273a65889"),
                            ProductNameEn = "Linear cutter stapler",
                            ProductNameFr = "استپلر برشی خطی",
                            ProductUrl = "Linear-cutter-stapler",
                            TypeId = new Guid("15f8dfc3-5c88-4a9e-be20-3ac476192583"),
                            isHotSale = false,
                            isManufactured = false
                        },
                        new
                        {
                            Id = new Guid("01756d04-f7c1-4815-ab5c-0555d9c62b35"),
                            ProductNameEn = "PPH stapler",
                            ProductNameFr = "استپلر هموروید",
                            ProductUrl = "PPH-stapler",
                            TypeId = new Guid("15f8dfc3-5c88-4a9e-be20-3ac476192583"),
                            isHotSale = true,
                            isManufactured = false
                        },
                        new
                        {
                            Id = new Guid("4ae1d802-87e4-40fe-b148-c624e8520bb1"),
                            ProductNameEn = "Skin stapler",
                            ProductNameFr = "استپلر پوستی",
                            ProductUrl = "Skin-stapler",
                            TypeId = new Guid("15f8dfc3-5c88-4a9e-be20-3ac476192583"),
                            isHotSale = false,
                            isManufactured = false
                        },
                        new
                        {
                            Id = new Guid("94e8c44c-b1e4-43b2-9748-c9ed815e597d"),
                            ProductNameEn = "Trocar",
                            ProductNameFr = "تروکار",
                            ProductUrl = "Trocar",
                            TypeId = new Guid("15f8dfc3-5c88-4a9e-be20-3ac476192583"),
                            isHotSale = false,
                            isManufactured = false
                        },
                        new
                        {
                            Id = new Guid("91db0db1-30b6-4934-8ab6-9bccdb0d4b74"),
                            ProductNameEn = "Spirometer Filter",
                            ProductNameFr = "فیلتر اسپیرومتری",
                            ProductUrl = "Spirometer-Filter",
                            TypeId = new Guid("65d34326-ce95-474e-96f7-850a6154fefb"),
                            isHotSale = true,
                            isManufactured = true
                        },
                        new
                        {
                            Id = new Guid("96043472-1394-414a-859b-dbae2ee0b9ca"),
                            ProductNameEn = "external nasal splint trapezium",
                            ProductNameFr = "اسپیلنت ذوذنقه",
                            ProductUrl = "external-nasal-splint-trapezium",
                            TypeId = new Guid("f464f47b-664f-476e-8d31-372b5cc6d488"),
                            isHotSale = true,
                            isManufactured = true
                        },
                        new
                        {
                            Id = new Guid("7d4756e1-f334-45a2-9cf4-b02c8de398bf"),
                            ProductNameEn = "surgery blade",
                            ProductNameFr = "تیغ جراجی",
                            ProductUrl = "surgery-blade",
                            TypeId = new Guid("e1b3d3c4-4b0b-4d86-a943-2cacc55ce7d2"),
                            isHotSale = true,
                            isManufactured = false
                        },
                        new
                        {
                            Id = new Guid("f2da3a12-5362-4c64-a5cc-3821a6f40502"),
                            ProductNameEn = "pain pomp",
                            ProductNameFr = "پمپ درد",
                            ProductUrl = "pain-pomp",
                            TypeId = new Guid("e1b3d3c4-4b0b-4d86-a943-2cacc55ce7d2"),
                            isHotSale = false,
                            isManufactured = false
                        },
                        new
                        {
                            Id = new Guid("9fbdbdfb-ebda-4c01-94b6-37df0b7f4233"),
                            ProductNameEn = "suture",
                            ProductNameFr = "سوچور",
                            ProductUrl = "suture",
                            TypeId = new Guid("e1b3d3c4-4b0b-4d86-a943-2cacc55ce7d2"),
                            isHotSale = false,
                            isManufactured = false
                        },
                        new
                        {
                            Id = new Guid("cadaf485-37c8-43c1-a784-8a1486d4b0d4"),
                            ProductNameEn = "Internal splint",
                            ProductNameFr = "اسپیلنت داخلی",
                            ProductUrl = "Internal-splint",
                            TypeId = new Guid("f464f47b-664f-476e-8d31-372b5cc6d488"),
                            isHotSale = true,
                            isManufactured = true
                        },
                        new
                        {
                            Id = new Guid("5bfa2312-a815-46e3-bb71-38c1d441d69b"),
                            ProductNameEn = "external nasal splint butterfly",
                            ProductNameFr = "اسپیلنت پروانه ای",
                            ProductUrl = "external-nasal-splint-butterfly",
                            TypeId = new Guid("f464f47b-664f-476e-8d31-372b5cc6d488"),
                            isHotSale = true,
                            isManufactured = true
                        });
                });

            modelBuilder.Entity("Entities.ProductDesc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductDescs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("45c2b927-6bc0-4a77-9d20-576c75d13be6"),
                            DescTitle = "کاربرد",
                            Description = "این فیلتر به منظور حفاظت از بیمار، تجهیزات و جریان تنفس در برابر انواع مختلف آلودگی ها و ذرات از جمله باکتری ها، ویروس ها و قطرات رطوبت ساخته شده است و کاربرد دارد. فیلتر آنتی باکتریال بین دهان یا ماسک با دریچه تقاضای انتودوکس قرار می گیرد",
                            ProductID = new Guid("b21aef73-8ded-4cc3-9aad-adfbd150bed5")
                        },
                        new
                        {
                            Id = new Guid("21fbc0ed-0dca-4afa-95d1-ec6637ee84aa"),
                            DescTitle = "کاربرد",
                            Description = "فیلترهای سیستم تنفس یکبار مصرف برای کاهش انتقال میکروبها و سایر ذرات موجود در بیهوشی در بخش مراقبت های ویژه استفاده میشوند. فیلترهای HME با حفظ حرارت و رطوبت بازدم ، عمل گرم کردن و رطوبت بخشیدن به گاز را فراهم می کنند. استفاده از این نوع فیلترها می تواند به طور موثر خطر عفونت هنگام بیهوشی و آلودگی تجهیزات تنفسی را کاهش دهد. همچنین مبدل حرارتی و رطوبت یکبار مصرف نوعی سیستم رطوبت است که در بیماران با تهویه مکانیکی و یا بیماران بیهوشی استفاده می شود تا به رطوبت ، گرم کردن، و فیلتر کردن گاز کمک کند. HME با فیلتر الکترواستاتیک برای محافظت در برابر میکروب ها به منظور کاهش انتقال ویروس ها و باکتری ها طراحی شده است تا خطر پنومونی ناشی از ونتیلاتور کاهش یابد.",
                            ProductID = new Guid("398b7e58-bbc3-456f-924e-074c264c4031")
                        },
                        new
                        {
                            Id = new Guid("f8186246-c76a-47a8-a5c6-27380bbb49b4"),
                            DescTitle = "فیلترهای HME کجا قرار می گیرند؟",
                            Description = "فیلترهای مبدل کننده حرارت و رطوبت بین مدار تنفس و قطعه Y (بین سیستم تنفس و بیمار) قرار می گیرند تا گرم کننده و مرطوب کننده مجاری تنفسی فوقانی را برای بیماران تحت مراقبت های ویژه فراهم کنند. مجاری تنفسی (بینی و دهان) به طور طبیعی هوای تنفسی ما را مرطوب می کند. هنگام استنشاق ، این راه های هوایی مرطوب شده و قبل از رسیدن هوا به ریه ها فیلتر می شوند. وقتی هوا از طریق بینی یا دهان ما استنشاق نمی شود ، به طور طبیعی گرم و مرطوب نمی شود . فیلترهای HME مهم و ضروری هستند زیرا به بیماران کمک می کنند که به تنهایی قادر به تنفس از طریق مجاری هوایی فوقانی نیستند.",
                            ProductID = new Guid("398b7e58-bbc3-456f-924e-074c264c4031")
                        },
                        new
                        {
                            Id = new Guid("ca0703ec-bdcd-4364-98a7-c818b2fd23cb"),
                            DescTitle = "فیلترهای HME چه کمکی میکند؟",
                            Description = "از باکتری و میکروب در مجاری تنفسی جلوگیری کرده\r\nاز گازهای بازدم شده بیمار برای گرم کردن و رطوبت هوای\r\nاستنشاق شده دوباره استفاده کرده از انسداد تنفسی جلوگیری کنید\r\nبهبود و کاهش خطر عوارض تنفسی را تضمین کنید.\r\nقطع شدن تهویه را به حداقل می رساند\r\nاز آلودگی متقابل بیمار و دستگاه خودداری می کند\r\nخطرات جابجایی کانولا و لوله را کاهش می دهد.\r\nفشار تنفسی را کاهش می دهد ",
                            ProductID = new Guid("398b7e58-bbc3-456f-924e-074c264c4031")
                        },
                        new
                        {
                            Id = new Guid("4635431e-61ac-4039-a6a1-845dbdad02b2"),
                            DescTitle = "کاربرد",
                            Description = "فیلترهای سیستم تنفس یکبار مصرف برای کاهش انتقال میکروبها و سایر ذرات موجود در بیهوشی و بخش مراقبت های ویژه استفاده میشوند. استفاده از این نوع فیلترها می تواند به طور موثر خطر عفونت و آلودگی تجهیزات تنفسی را کاهش دهد. این فیلترها در اسپیرومتری مورد استفاده قرار می گیرند تا اسپیرومتر از آلودگی قطرات عفونی محافظت شود.",
                            ProductID = new Guid("91db0db1-30b6-4934-8ab6-9bccdb0d4b74")
                        },
                        new
                        {
                            Id = new Guid("4c2012f1-bd7c-4cc9-a887-d2de94159451"),
                            DescTitle = "نحوه استفاده",
                            Description = "نحوه استفاده از آن بدین شکل میباشد که یک سر فیلتر اسپیرومتری به دستگاه وصل میگردد و سر دیگر آن در دهان بیمار قرار میگیرد.هوا از طریق این فیلتر وارد دستگاه شده ، میزان هوای موجود در ریه فرد و سرعت تنفس او مورد بررسی قرار میگیرد. فیلتر های اسپیرومتری حاوی پودر جاذب آنتی باکتریال میباشند ،لذا از انتقال عفونت و ترشحات جلوگیری میکنند.",
                            ProductID = new Guid("91db0db1-30b6-4934-8ab6-9bccdb0d4b74")
                        },
                        new
                        {
                            Id = new Guid("1bd85e75-9d00-4b12-8b90-3594e92531f9"),
                            DescTitle = "تست اسپیرومتری چیست؟",
                            Description = "این تست جهت سنجش عملکرد ریه جهت اندازه گیری جریان خروجی و ورودی به ریه انجام میگردد.جهت انجام تست اسپیرومتری، فرد نشسته و از طریق یک فیلتر آنتی باکتریال اسپیرومتری،داخل دستگاه میدمد.دستگاه میزان هوای ورودی هنگام دم و بازدم و همچنین سرعت جریان تنفس را اندازه گیری مینماید.",
                            ProductID = new Guid("91db0db1-30b6-4934-8ab6-9bccdb0d4b74")
                        },
                        new
                        {
                            Id = new Guid("b0bb28a4-1bb3-4f80-9bd9-f49f0ca48dc4"),
                            DescTitle = "نگهداری از اسپلیت بینی خارجی",
                            Description = "دوران نقاهت جراحی بینی ۷ الی ۱۰ روز است و باید طی این مدت مراقب اسپلینت بینی و پانسمان بینی باشیم.\r\nاز رفتن به مکان هایی که شلوغ است و امکان ضربه خوردن به بینی وجود دارد اجتناب نمایید.\r\nهنگام تمیز کردن صورت از پنبه یا دستمال مرطوب استفاده نمایید.\r\nهنگام استحمام بعد از جراحی بینی مراقب باشید که پانسمان بینی به هیچ عنوان خیس نشود چرا که باعث ایجاد حساسیت پوست بینی و خارش خواهد شد.\r\nنکته قابل ذکر این است که برای این باید مراقب اسپلینت بینی بود که جابه جایی آن باعث می شود که نتیجه جراحی بینی دستخوش تغییراتی شود.",
                            ProductID = new Guid("96043472-1394-414a-859b-dbae2ee0b9ca")
                        },
                        new
                        {
                            Id = new Guid("efcc6eed-4f6e-4b15-b899-9496c2717dd4"),
                            DescTitle = "کاربرد",
                            Description = "اسپلینت سیلیکونی داخلی برای برخی بیماران با صلاحدید جراح استفاده می شود. به طور معمول در جراحی های رفع انحراف تیغه میانی بینی و ترمیم بینی (جراحی پلاستیک بینی) مورد استفاده قرار می گیرند. تامپون سیلیکونی بینی تیغه میانی بینی و استخوان های دیواره بینی را در مدت بهبودی محافظت می کند، با فشار وارده بر پوست و مخاط بینی خونریزی را کنترل نموده به بهبود همزمان ساختار داخلی بینی و دیواره نیز کمک کند. بیشتر جراحان زیبایی بینی برای آن که نتیجه جراحی بینی مطلوب باشد، همزمان با اسپلینت و آتل خارجی بینی از اسپلینت های داخلی نیز استفاده می نمایند. اسپلینت‌ های داخل بینی ممکن است پس از ۳ تا ۵ روز بعد از عمل و با تشخیص جراح برداشته شوند.",
                            ProductID = new Guid("cadaf485-37c8-43c1-a784-8a1486d4b0d4")
                        },
                        new
                        {
                            Id = new Guid("1c5eb321-5451-4cfe-8111-d86e9aa0fe74"),
                            DescTitle = "روش استفاده از تامپون سیلیکونی بینی",
                            Description = "پس از اتمام جراحی و تمیز کردن خون و ترشحات، تامپون ها را از بسته باز نموده، با سرم فیزیولوژی شستشو داده شده و به طور قرینه در داخل بینی قرار داده می شود. باید به این نکته توجه داشت که تامپون سیلیکونی را از قسمت باریکتر وارد نموده تا در قسمت فوقانی بینی قرار گیرد و انتها که پهن تر بوده و سوراخی در آن تعبیه شده در قسمت پایین بینی واقع شود. همچنین قسمت تخت پشت (به طرف صورت) قرار گرفته و قسمت گرد به طرف جلو (روربروی صورت) قرار گیرد.",
                            ProductID = new Guid("cadaf485-37c8-43c1-a784-8a1486d4b0d4")
                        },
                        new
                        {
                            Id = new Guid("cf221a2d-cc55-4e22-825d-57f7a04f1d43"),
                            DescTitle = "مزایای استفاده از اسپلینت داخل بینی سیلیکونی",
                            Description = "تیغه میانی بینی را به دلیل سست بودن تا زمانی که نیاز است، محافظت می کند.\n\nاز خونریزی های احتمالی بعد از جراحی بینی جلوگیری می نماید.\n\nراه هوایی بینی در مدت استفاده باز می ماند. (شیار داخلی تامپون راه تنفس را باز نگاه می دارد)\n\nخون و ترشحات ایجاد شده را به وسیله شیار موجود از سینوس به خارج بینی انتقال می دهد.",
                            ProductID = new Guid("cadaf485-37c8-43c1-a784-8a1486d4b0d4")
                        },
                        new
                        {
                            Id = new Guid("5d45d919-a071-4b1f-9386-42487d0bc29e"),
                            DescTitle = "کاربرد فیلتر آنتی باکتریال",
                            Description = "فیلترهای باکتریایی و ویروسی (B/V) به کاهش انتقال میکروب ها و سایر ذرات معلق در سیستم تنفسی بیمار کمک می کند. فیلترهای B/V با ارائه فیلتراسیون بسیار کارآمد، سبک هستند و برای کاهش کشش در سیستم تنفس و اطمینان از راحتی بیمار، شکل دارند و به کاهش انتقال میکروب ها و سایر ذرات معلق در سیستم تنفسی کمک می کنند.\nشکل ارگونومیک گرد و بدون لبه های تیز، علامت گذاری فشار را کاهش می دهد. همچنین بخاطر طراحی سبکی که دارند، باعث کاهش فشار ایجاد شده بر روی سیستم تنفسی می شود. علاوه بر این موارد این فیلتر ها با همراه داشتن یک فیلتر الکترواستاتیک HMEF برای محافظت از بیماران در برابر عفونت ها استفاده می شوند و گازهای ورودی را گرم و مرطوب می کند.\nاین فیلتر ها از یک محفظه الکترواستاتیک ساخته شده که برای استفاده طولانی مدت طراحی شده اند. فیلتر های باکتریایی و ویروسی موجود در دستگاه برای کمک به جلوگیری از انتقال باکتری ها و ویروس ها و جلوگیری از عبور عفونت به بیمار در حین بیهوشی یا برای انواع دیگر تهویه محیط، طراحی شده اند.",
                            ProductID = new Guid("b21aef73-8ded-4cc3-9aad-adfbd150bed5")
                        },
                        new
                        {
                            Id = new Guid("54358b15-7f51-4aaa-aa12-78a3413cc0cd"),
                            DescTitle = "مشخصات فیلتر آنتی باکتریال",
                            Description = "محیط فیلتر از الیاف هیدروفوبیک با شارژ دائمی ساخته شده است که به افزایش کارایی جذب ذرات کمک می کند و حتی اگر خیس باشد مقاومت تنفسی کم و پایداری ایجاد می کند. همه مواد انتخاب شده در تولید محصول با محیط زیست سازگار هستند و فیلترها با اتصالات استاندارد طراحی شده اند تا به سهولت اتصال، به دستگاه های مختلف تهویه و بیهوشی کمک کنند.\r\nفیلترهای ویروسی و باکتریایی با خاصیت نمونه گیری گاز کربن دی اکسید و یا بدون نمونه گیری در دسترس و قابل تهیه می باشند. این طیف گسترده از فیلترها، دستگاه هایی با کیفیت بالا می باشند که سطح بالایی از فیلتراسیون و رطوبت هوای مرطوب را در سراسر محدوده استفاده، ایجاد می کنند. تمام HMEF ها و فیلترها شامل (لویر پورت) برای نمونه گیری آسان گاز با درپوش اتصال دهنده هستند",
                            ProductID = new Guid("b21aef73-8ded-4cc3-9aad-adfbd150bed5")
                        },
                        new
                        {
                            Id = new Guid("99e6e54b-985e-4ec3-93de-c9defe27581a"),
                            DescTitle = "ویژگی استپلر حلقوى ",
                            Description = "طراحى و اختراع منحصر به فرد استپلر حلقوى جراحی با یک رهاسازى ایمن خودکار قابل شنیدن، اطمینان یک تجسم دقیق و ثابت در هنگام نزدیک کردن و فشرده سازى بافت را مى دهد.",
                            ProductID = new Guid("b380acf2-45d4-40cc-8413-2b0c38666e3b")
                        },
                        new
                        {
                            Id = new Guid("de0ede98-dfc5-40b7-8b2d-7eaec49c5878"),
                            DescTitle = "کاربرد استپلر حلقوی",
                            Description = "استفاده از استپلر حلقوی بیشتر در جراحی های عمومی، عمل های مربوط به درمان چاقی مثل جراحی بای پس و اسلیو معده، عمل ها و جراحی های قفسه سینه، جراحی های مربوط به راست روده و روده بزرگ و در آخر انجام آناستاموز انتها به انتها استفاده می شود. بیشتر مرسوم است که از این استپلر برای درمان هموروئید و بواسیر استفاده شود.",
                            ProductID = new Guid("b380acf2-45d4-40cc-8413-2b0c38666e3b")
                        },
                        new
                        {
                            Id = new Guid("dfe2c057-097f-41db-80a1-734048335b7e"),
                            DescTitle = "مزیت استفاده از استپلر ها حلقوی",
                            Description = "دسته های شلیک استپلر حلقوی هوروئید به گونه ای ارگونومیک طراحی می شود و به هین دلیل استفاده از این استپلر ها در هنگام جراحی بسیار آسان تر و دقیق تر خواهد بود......در طراحی و تولید استپلر حلقوی یک مکانیزم قفل ایمنی دوگانه در دستگاه قرار می گیرد که باعث می شود هنگام بخیه بافت مورد نظر بدن بیمار به هم نریزد.....امکان بخیه زدن بافت ها نسبت به روش های سنتی آسان تر خواهد شد و در نتیجه مدت زمان عمل جراحی بیمار کاهش می یابد......در کل اگر از روش های مانند لاپاراسکوپی که در آن استپلر حلقوی استفاده می شود برای جراحی استفاده شود بیمار در کمتری را نسبت به جراحی با تیغ یا روش ها تهاجمی دیگر تحمل خواهد کرد......دراین دستگاه ها دو ردیف کارتریج شفاف با منگنه هایی از جنس تیتانیوم طعبیه شده و بافت ها اضافی ایجاد شده را فشرده می کند تا یک آناستوموز دایره ای ایجاد کند.......با استفاده از هموروئیدکتومی منگنه ای درصد احتمال ایجاد عفونت کاهش می یابد.....قبل از شلیک توسط منگنه بافت بطور ملایم فشرده سازی می شود و در نتیجه ضربه کمتری را تحمل می کند. علاوه بر آن تغییر مکان استپلر نیز کمتر می شود.......بیمار بعد از عمل همورویید نیاز به بستری نخواهد داشت",
                            ProductID = new Guid("b380acf2-45d4-40cc-8413-2b0c38666e3b")
                        },
                        new
                        {
                            Id = new Guid("bc1fdfb1-894d-4c67-bbb3-cfeb18341f86"),
                            DescTitle = "ویژگی ها",
                            Description = "1. سر قوس مخصوص.... 2. چهار ردیف منحنی استین با یک برش واحد بین..... 3. دسترسی به لگن پایین با اثر روش خوب را فراهم می کند.... 4- دید بهتر و کارکرد آسان.... 5- برش و جمع کردن همزمان ، برداشتن راست روده دیستال را ساده کنید..... 1. آسان و ساده برای کار..... 2. می تواند مؤلفه نوسان کننده را با یک ابزار تغییر دهد..... 3. تیتانیوم وارداتی ، استحکام بالاتر و استرس کششی را فراهم می کند..... 4- دریل شکل دهی یکپارچه برای اطمینان از شکل و کلیت تیتانیوم..... 5- برای کاهش خونریزی ، ردیف های دوتایی از عناصر تیتانیوم تهیه کنید...... 6. شکل منحنی منحصر به فرد برای داشتن نمای لاپاروسکوپی گسترده از راست روده تحتانی در لگن عمیق.",
                            ProductID = new Guid("fd955430-0230-4f1d-92f5-bcaded597262")
                        },
                        new
                        {
                            Id = new Guid("eb7d898d-f6b8-421b-bc89-23b72139c481"),
                            DescTitle = "نکات مهم ",
                            Description = " 1- این ابزار فقط توسط پزشکانی که آموزش کافی دریافت کرده اند و با مهارت های عملیاتی آشنا هستند ، قابل استفاده است.....2- هنگام برداشتن ابزار ، حتماً بافت بخیه شده را برای خونریزی بررسی کنید.در صورت وجود خونريزي ، روشهاي مناسبي براي كاهش خونريزي وجود دارد......3. لطفا بسته را قبل از استفاده با دقت بررسی کنید؛استفاده از این بسته در صورت آسیب دیدن ممنوع است.....4- محصول توسط اتیلن اکسید استریل شده است و مدت اعتبار آن برای استریلیزاسیون سه سال است ، بنابراین لطفاً بررسی کنید که آیا محصول در طول مدت اعتبار است یا خیر.اگر مدت اعتبار منقضی شود ، از محصول استفاده نمی شود...... 5- محصول فقط برای یکبار مصرف است ، به طوری که حتی با عقیم سازی مجدد قابل استفاده مجدد نیست.",
                            ProductID = new Guid("fd955430-0230-4f1d-92f5-bcaded597262")
                        },
                        new
                        {
                            Id = new Guid("0ccaef04-934c-46fe-bc43-0e842bc9ff22"),
                            DescTitle = "توضیحات",
                            Description = "یکبار مصرف برش خمیده یکبار مصرف مکانهایی است که دو ردیف متراکم از استیپل تیتانیوم وجود دارد و به طور همزمان بافت را به جای دوخت دستی به طور همزمان بین دو ردیف مشکی تقسیم می کند.این می تواند زمان عمل و خونریزی را کاهش دهد.سهولت استفاده و بهبود کیفیت عملکرد.یکبار مصرف محصول از صلیب جلوگیری می کند. این صید کننده برش خمیده مناسب برای از بین بردن و برش آناستوموز در جراحی کانال هوایی استفاده می شود.",
                            ProductID = new Guid("fd955430-0230-4f1d-92f5-bcaded597262")
                        },
                        new
                        {
                            Id = new Guid("e47d4a7f-29bd-4868-a42d-3d1d0c3c544e"),
                            DescTitle = "کاربرد اندوبگ جدا شونده",
                            Description = "برای جمع آوری ضایعات و بازیابی نمونه در جراحی عمومی، جراحی روده بزرگ، جراحی قفسه سینه، اورولوژی، جراحی آندوسکوپی زنان یا سایر موارد استفاده می شود. قابل کاربرد در تروکارهای ۱۰ ، ۱۱ ، ۱۲ ، ۱۵ میلی متری می باشد.",
                            ProductID = new Guid("c4821c34-c92c-4a0f-a94b-bfd4ad6cfd8b")
                        },
                        new
                        {
                            Id = new Guid("b59035d4-d8d2-4c5d-bf7f-082f12d38f41"),
                            DescTitle = "مشخصات کلی محصول",
                            Description = "دسته ای که به راحتی در دست گرفته می شود-----شفت لوله ای امکان کشش و استقرار یکنواخت را فراهم می کند-----شفت لوله ای امکان کشش و استقرار یکنواخت را فراهم می کند-----Rip-stop و نشت از کیسه TPU برای استحکام و امنیت بالاتر جلوگیری می کند------کیسه قابل توجه، حجم متفاوت برای قرار دادن طیف گسترده ای از اندازه نمونه------استفاده از PU در جنس این مدل از اندوبگ ها جهت عدم نشت مایعات",
                            ProductID = new Guid("c4821c34-c92c-4a0f-a94b-bfd4ad6cfd8b")
                        },
                        new
                        {
                            Id = new Guid("8a1c3a34-870b-4ba5-95a8-e035c1b2bcbf"),
                            DescTitle = "ویژگی های محصول",
                            Description = "تکنیک منحصر به فرد ثبت شده، جدا شدن سریع و آسان کیف از دسته را تضمین می کند. طراحی دسته ارگونومیک امکان چرخش صاف و دستکاری محصول را می دهد. حلقه فلزی تقویت شده به طور مداوم باز شدن کیف را تضمین می کند و هنگام بارگیری نمونه، کیف را در محل خود نگه می دارد. کیسه توقف با اندازه مناسب از شکستگی و نشت جلوگیری می کند.",
                            ProductID = new Guid("c4821c34-c92c-4a0f-a94b-bfd4ad6cfd8b")
                        },
                        new
                        {
                            Id = new Guid("b36e4039-b0c4-4ab9-b08c-90ff053a3c56"),
                            DescTitle = "توضیحات محصول",
                            Description = "استخراج مطمئن، ساده. سیستم کیسه بازیابی نمونه ENDO BAG از دو بازوی پشتیبانی برای تسهیل باز شدن کیسه و جذب بافت در طول روش های لاپاراسکوپی استفاده می کند. هر دو کیف و بازوهای نگهدارنده به شفت و مقدمه متصل شده اند، بنابراین از رتریور به راحتی می توان برای استخراج نمونه ها استفاده کرد.",
                            ProductID = new Guid("c4821c34-c92c-4a0f-a94b-bfd4ad6cfd8b")
                        },
                        new
                        {
                            Id = new Guid("8c8af893-a829-43ed-853b-8c3a0f170088"),
                            DescTitle = "مورد استفاده استاپلر GIA اندوسکوپی",
                            Description = "اغلب در طول جراحی های لاپاراسکپیک آپاندکتومی و برداشت معده و روده کاربرد دارد . هم چنین در جراحی های اندوسکوپیک توراکس وزنان نیز به کار می رود .",
                            ProductID = new Guid("58c1f884-560a-4433-8467-6df7d7779aa8")
                        },
                        new
                        {
                            Id = new Guid("2493ec86-43ea-4aa2-8bb1-982f224d7efc"),
                            DescTitle = "ویژگی های محصول",
                            Description = "کارتریج ها ی آن دارای دو ردیف سه تایی منگنه است که یک چاقو در بین این دوردیف قرار دارد . بسته به نوع بافت ، از طول های مختلف آن استفاده می شود. این استاپلر در سایز های 30.45.60 میلی متری موجود است .",
                            ProductID = new Guid("58c1f884-560a-4433-8467-6df7d7779aa8")
                        },
                        new
                        {
                            Id = new Guid("de0d33b1-9d11-4573-b73e-76148f99e527"),
                            DescTitle = "معرفی",
                            Description = "استاپلر GIA اندوسکوپی ( ENDO GIA STAPLER ) : نوعی استاپلر یک بار مصرف باقابلیت تعویض کارتریج است که دارای باز و قابلیت چرخش است .",
                            ProductID = new Guid("58c1f884-560a-4433-8467-6df7d7779aa8")
                        },
                        new
                        {
                            Id = new Guid("3f3f5851-9b13-4640-a959-f028d5cf1218"),
                            DescTitle = "ویژگی ها ",
                            Description = "کارتریج 6 ردیفه برای همه سایز های استپلر  که باعث تامین امنیت بالا د تیغه فوقانی میشود..................عرض مناسب دهانه باز گیره برای جایگداری اسان بافت ....................بدنه در ابعاد مختلف .............کنترل دهانه (با کشیدن اهرم و کارتریج با همدیگر استپلر آماده شلیک است...................زاویه چرخش کامل 360 درجه برای سهولت دسترسی به بافت ها............... طراحی ارگونومیک دسته شلیک کننده ",
                            ProductID = new Guid("6488e50c-b8a0-4af8-9d65-71366156b106")
                        },
                        new
                        {
                            Id = new Guid("58d0dabb-e55f-4d91-9756-8db8f07ed6d8"),
                            DescTitle = "کاربرد",
                            Description = "مناسب برای انتقال ، برداشتن و یا بازسازی در آناستوموز. می توان در انواع جراحی عمومی باز یا حداقل تهاجمی ، زنان و زایمان ، ارولوژی ، جراحی سینه و جراحی کودکان استفاده کرد. می توان با داروی آناستوموز یا نگهدارنده بافت استفاده کرد. همچنین می توان از آن برای برش و برداشتن بافت پارانشیمی کبد (سیستم عروقی کبدی و ساختار صفراوی) ، لوزالمعده ، کلیه و طحال استفاده کرد.",
                            ProductID = new Guid("6488e50c-b8a0-4af8-9d65-71366156b106")
                        },
                        new
                        {
                            Id = new Guid("23f2b597-57ac-49e9-8e99-a0d95dc28bfa"),
                            DescTitle = "مشخصات منگنه",
                            Description = "1. تیغه برش یکبار مصرف باید همراه با بارگیری تعویض شود تا اطمینان حاصل شود که همیشه تیغه تیز است تا بتواند بافت را به طور صحیح برش دهد و آسیب های بافت را کاهش دهد. 2- مکانیسم کانتورل برای ترخیص کالا از گمرک معادل اطمینان حاصل می کند که قطعات در انتهای دور و انتهای مجاورت در واحد بارگیری یکنواخت هستند. 3. با باز شدن قدامی گسترده ای از واحد بارگیری ، می توان از بافت راحت الهام گرفت. طراحی بوم نازک باعث می شود ورود بدون جداسازی بیشتر از فاصله بزرگتر باشد ، به طوری که آسیب های بافتی از بین بروند. 4. با 360 چرخشی ، لیت برای رسیدن به بافت راحت است. 5- با طرح متقارن - ارگونومیک ، عمل جراحی را می توان به طور مستقل با دست چپ و راست انجام داد. 6. همه مدل ها می توانند از طریق تروکار 12 میلی متری عبور کنند.",
                            ProductID = new Guid("6488e50c-b8a0-4af8-9d65-71366156b106")
                        },
                        new
                        {
                            Id = new Guid("4f0f0275-f077-4cf4-adc3-f517fb0602bb"),
                            DescTitle = "توضیحات ",
                            Description = "برای جراحی ، برداشتن و ایجاد آناستوموز در جراحی های لاپاراسکوپی قابل استفاده است.",
                            ProductID = new Guid("6488e50c-b8a0-4af8-9d65-71366156b106")
                        },
                        new
                        {
                            Id = new Guid("c69ab759-277a-4d7c-8bfa-73e36fdd7f1f"),
                            DescTitle = "لیگا کلیپس یا کلیپس جراحی",
                            Description = "این ابزار برای قطع خونریزی در زمان عمل جراحی به کار می رود که از جنس تیتانیوم یا مواد پلیمری تهیه می شود. قبل از این از روش کوتر برای بریدن یا سوزاندن رگ های خونی استفاده می شد که مضرات زیادی را برای بیمار داشت. امروزه از لیگا کلیپس یا سرجری کلیپس استفاده می شود.از این کلیپس در جراحی های عمومی از جمله لاپاراتومی و لاپاراسکوپی به کار می رود.",
                            ProductID = new Guid("59ec2c5b-e639-40da-b7b8-95a6d31f2d6d")
                        },
                        new
                        {
                            Id = new Guid("63e20bd5-085c-406f-884c-7a21fdb95da8"),
                            DescTitle = " ویژگی های لیگا کلیپس چیست؟",
                            Description = "این ابزار از جنس تیتانیوم است. وجود شیارهای آتروماتیک مانع از این می شود که به بافت داخلی بیمار آسیب وارد شود. این شیارها بر روی رگ های خونی بیمار ثابتند. پزشک برای اینکه این کلیپس را در بدن بیماران قرار دهد از دستگاه های مخصوص پزشکی استفاده می کند. این ابزار در ابعاد مختلف تولید می شود به همین دلیل پزشک می تواند انواع آن را برای بیماران به کار ببرد.",
                            ProductID = new Guid("59ec2c5b-e639-40da-b7b8-95a6d31f2d6d")
                        },
                        new
                        {
                            Id = new Guid("4e162357-2b04-454b-86db-d25a52244087"),
                            DescTitle = "موارد استفاده",
                            Description = "پزشک در طول انجام هیسترکتومی برای اینکه تخمدان یا رحم را جدا کند به چندین ابزار جراحی و گیره نیاز دارد. این ابزارها به عروق خونی فشار می آورند و خونرسانی به قسمت آناتومیک بدن را قطع می کنند. سپس پژشک می تواند قسمتی که آسیب دیده را در بیمار پیدا کند و آن را درمان کند.در لاپاراتومی هم پزشک یک شکاف در ناحیه شکم بیمار وارد می کند و بر روی قسمت مورد نظر مثل معده، روده، آپاندیس و… می توان جراحی را انجام داد. به طور کلی از لیگا کلیپس برای قطع خون رسانی در عمل جراحی های عمومی، جراحی قفسه سینه، جراحی زنان، اورولوژی و جراحی های مویرگی استفاده می شود.",
                            ProductID = new Guid("59ec2c5b-e639-40da-b7b8-95a6d31f2d6d")
                        },
                        new
                        {
                            Id = new Guid("8094699a-0cc3-4d70-8ee1-0ee3599b0423"),
                            DescTitle = "لیگاشور",
                            Description = "سیستم لیگاشور شامل یک ژنراتور بایپولار رادیوفرکانسی و یک اپلایر (فورسپس) است. فورسپس لیگاشور ، شبیه به یک کلمپ است .",
                            ProductID = new Guid("dd713b1e-379b-43d3-a59e-571c6230ff86")
                        },
                        new
                        {
                            Id = new Guid("d4230f74-c985-4377-92c4-ab3ace28ad2d"),
                            DescTitle = "انواع اپلایر لیگاشور",
                            Description = "1) اپلایرpean-style…هفت اینچی (ligasure standard)     ......     2)اپلایر heaney-style … نه اینچی (ligasure max)      ......      3)گراسپر/دیسکتور لاپاروسکوپیک maryland …پنج میلی متری (لیگاشویی لاپاروسکوپی)",
                            ProductID = new Guid("dd713b1e-379b-43d3-a59e-571c6230ff86")
                        },
                        new
                        {
                            Id = new Guid("7f2f9975-02a0-43a8-9ec8-c51fc8837bc7"),
                            DescTitle = "مورد استفاده",
                            Description = "دستگاه لیگاشور با ایجاد یک جریان باپیولار ، کوآگولاسیون عروق می گردد .بااستفاده از این وسیله ، والاسین موجود در دیواره رگ  به هم می چسبدوسبب مسدود شدن دایمی رگ می گردد.برای دیدن سیستم لیگاشور بروی لینک زیر کلیک کنید .خون و بافت میتواند روی آرواره های آن خشک شود بنابر این ممکن است نیاز به پاک کردن دوره ای آن (بایک اسپانج مرطوب) باشد.",
                            ProductID = new Guid("dd713b1e-379b-43d3-a59e-571c6230ff86")
                        },
                        new
                        {
                            Id = new Guid("6a342839-2cb3-4d8b-ac4b-9d548864839c"),
                            DescTitle = "ویژگی ",
                            Description = "افزایش سرعت جراحی ..................اثر بخشی و دقت..................نیاز به بخیه و نخ بخیه نیست ............میزان خونریزی را به حد اقل میرساند. ............... کاهش در هزینه بیمار",
                            ProductID = new Guid("dd713b1e-379b-43d3-a59e-571c6230ff86")
                        },
                        new
                        {
                            Id = new Guid("d8dee4ba-211f-4d36-9b8e-fdf3e63fa433"),
                            DescTitle = "استپلر یک بار مصرف خطى برشی",
                            Description = "استپلر خطى برشی یک بار مصرف براى هر بیمار به دقت به منظور برش، برش عرضى و استپلر شکمى، زنان و زایمان، کودکان و جراحى هاى قفسه سینه طراحى شده است. تمرکز در درجه اول در عملکرد عالى، قابلیت اطمینان و کارایى برتر به ما این اطمینان را مى دهد که کاربر از تجربه اى بى عیب و نقص برخوردار مى شود. برش خطى XNY یک برش فوق العاده نرم و فرمول خط گیره ایمن را در میان تمامى رِنج NOVA به ارمغان مى آورد.",
                            ProductID = new Guid("106f346e-b5e9-4117-b6e1-eb0273a65889")
                        },
                        new
                        {
                            Id = new Guid("281c6564-9377-4fc3-8bfa-9767b315bf06"),
                            DescTitle = "ویژگی ها",
                            Description = "فولاد ضدزنگ محكم فوق العاده تيز آمريكايى با درجه پزشكى  440................ دو جايگاه ميانى (جلو و عقب) كه با ترجيحات متفاوت جراح وفق داده مى شود..................عملكرد فوق العاده و نرم با منگنه هاى B شكل عالى.................فرمول ايمن خط منگنه، با 4 منگنه اطراف خط برداشت....................ساخته شده با مكانيسم قفل ايمن...................كارتريج هاى مختلف براى انواع ضخامت بافت موجود مى باشد",
                            ProductID = new Guid("106f346e-b5e9-4117-b6e1-eb0273a65889")
                        },
                        new
                        {
                            Id = new Guid("fe793e4c-a75b-404c-9380-051c17715686"),
                            DescTitle = "استاپلر یا هموروئید پکسی (pph)",
                            Description = "یکی از روشهای درمان این بیماری است. هموروئید پکسی (pph) در دسته روشهایی است کمتر تجویز میشود، زیرا این روش عوارض و خطرات بسیاری را به همراه دارد",
                            ProductID = new Guid("01756d04-f7c1-4815-ab5c-0555d9c62b35")
                        },
                        new
                        {
                            Id = new Guid("dab31586-5fb6-4a2a-a911-a4b97dc2dd54"),
                            DescTitle = "توضیحات",
                            Description = "هموروئید پکسی یکی از روش های هموروئیدکتومی است که معمولاً در درمان هموروئیدهای داخلی درجه ۳ و ۴ با عود مکرر کاربرد دارد. یعنی این روش در درمان هموروئید خارجی کاربرد ندارد.برای درمان هموروئید به روش استاپلر باید در بیمارستان بستری شوید. جراحی به دلیل درد زیادی که ایجاد میکند باید تحت بیهوشی انجام شود.در این روش که با استفاده از ابزاری مخصوص انجام می شود، در ابتدا عروق هموروئیدی به نقطه ای بالاتر منتقل می شوند. سپس با استفاده از دستگاهی مخصوص زائده های هموروئیدی قطع میشوند، این روش به شدت دردناک بوده و عوارض بسیاری را به همراه خواهد داشت.",
                            ProductID = new Guid("01756d04-f7c1-4815-ab5c-0555d9c62b35")
                        },
                        new
                        {
                            Id = new Guid("8ce9311a-45f6-49a4-a031-07f795f78ca5"),
                            DescTitle = "مزایای درمان با استاپلر",
                            Description = "درد کمتر در مقایسه با جراحی سنتی...............دوران نقاهت کوتاه مدت",
                            ProductID = new Guid("01756d04-f7c1-4815-ab5c-0555d9c62b35")
                        },
                        new
                        {
                            Id = new Guid("543f2e3a-e042-4a1a-8e42-c60e0e617b51"),
                            DescTitle = "معایب استاپلر",
                            Description = "خونریزی       بی اختیاری مقعد.........آسیب دیدن دیواره مقعدی.......عفونت........احساس ناکامل بودن دفع............مشکلات مربوط به اجابت مزاج...............زخم مقعدی................واکنش به داروهای بی حسی..............تنگ شدن مقعد.............خطر عود مجدد بیماری",
                            ProductID = new Guid("01756d04-f7c1-4815-ab5c-0555d9c62b35")
                        },
                        new
                        {
                            Id = new Guid("585eef2c-cd0b-4409-ad91-1417f30951d8"),
                            DescTitle = "مزایا",
                            Description = "پیوند بهتر لبه‌های زخم به یکدیگر  .................زیبایی پوست بعد از بهبود.................استریل بودن دستگاه و در نتیجه کاهش احتمال عفونت...................قابلیت جابجایی به دلیل کم حجم و سبک بودن...............نداشتن تحریک بافتی در پوست آسیب دیده.......................کاهش خونریزی در زمان پیوند زدن..................امکان استفاده از آن بوسیله آندوسکوپ",
                            ProductID = new Guid("4ae1d802-87e4-40fe-b148-c624e8520bb1")
                        },
                        new
                        {
                            Id = new Guid("04b433a2-8b95-46bb-b0fa-ea19e5e430e5"),
                            DescTitle = "استپلر پوستی چیست؟",
                            Description = "استپلر پوستی یک دستگاه کوچک و قابل حمل است که به‌جای بخیه کردن از آن استفاده می‌شود. این ماشین دوخت می‌تواند لبه‌های زخم را به هم نزدیک کند. استاپلر پوستی از پلاستیک PVC تولید می‌شود و تعداد زیادی سوزن منگنه‌ی استیل در آن گذاشته می شود.از استپلر پوستی بیشتر برای نواحی رویش مو و فرق سر استفاده می‌شود. در این قسمت پزشک به نخ بخیه و سوزن زدن نیاز ندارد. از سوی دیگر نیاز نیست تا لبه‌های زخم به یکدیگر نزدیک شوند. در روش قدیمی بخیه زدن، با نزدیک کردن لبه‌های زخم فشار زیادی به آن وارد می‌شد. گاهی هم زخم بر اثر فشار مجدداً خونریزی می‌کرد که بخیه زدن عملاً با مشکل مواجه می‌شد.اما حالا استپلر پوستی به مدد جراحان آمده است تا بتوانند براحتی و با سرعت بیشتری زخم‌های بیماران را بخیه بزنند.",
                            ProductID = new Guid("4ae1d802-87e4-40fe-b148-c624e8520bb1")
                        },
                        new
                        {
                            Id = new Guid("2da6507f-d236-4f10-9233-3a304286b342"),
                            DescTitle = "ویژگی‌های استپلر پوستی ",
                            Description = "این وسیله‌ی کاربردی دارای دقت و سرعت عمل بالایی در بستن زخم‌های بیماران است. پزشک می‌تواند سوزن منگنه آن را در سه نوع پهن، بلند و یا استاندارد تهیه کند.از سایر مزایای استاپلرها سرعت عمل ، دقت و یکنواختی بستن زخم می باشد. سوزن منگنه آنها در سه نوع استاندارد ، پهن و بلند وجود دارد و درون دستگاه بین ۱۵ تا ۵۵ سوزن منگنه بسته به مدل آن وجود دارد.در این وسیله سوزن با وسیله‌ی مخصوص برداشته می‌شود. در نتیجه مرحله‌ی بخیه کشیدن ندارد و بیمار درد کمتری را احساس می‌کند.این دستگاه از ۴ قسمت سوزن استپلر، سوزن گذاری، قسمت پیش قفل شونده و سوزن استپلر بلند تشکیل شده است. سوزن استپلر هر چقدر که تیز باشد، آسیب کمتری به بافت پوست وارد می شود. اگر سوزن‌گذاری بدون وقفه و با سرعت بالا انجام شود، فشردگی بخیه‌زدن کمتر می‌شود.پیش قفل شونده در این دستگاه کوچک به منظور جایگذاری دقیق سوزن استپلر کاربرد دارد. همچنین در این دستگاه یک سوزن استپلر بلند نیز استفاده می‌شود. این سوزن برای برداشتن راحت‌تر سوزن با درد کمتر کاربرد دارد.",
                            ProductID = new Guid("4ae1d802-87e4-40fe-b148-c624e8520bb1")
                        },
                        new
                        {
                            Id = new Guid("b3c472bb-54ab-4c62-9f59-88014db8accd"),
                            DescTitle = "انواع استاپلر پوستی",
                            Description = "استاپلر پوستی شامل دو نوع یک بار مصرف و چند با مصرف است. استاپلرهای یکبار مصرف استریل شده هستند که بعد از یک بار استفاده باید دور انداخته شوند. در ستپلر پوستی چند بار مصرف پزشک می‌تواند منگنه را به صورت مجزا تهیه و در داخل این ماشین کوچک قرار دهد.در انواع استپلر پوستی ۳۵ سوزن استپلر قرار داده می‌شود. تعداد استپلرهایی که در زمان پیوند زخم استفاده می‌شود، به مقدار آن بستگی دارد.",
                            ProductID = new Guid("4ae1d802-87e4-40fe-b148-c624e8520bb1")
                        },
                        new
                        {
                            Id = new Guid("1212afe2-3e0f-4fd2-b33f-f11fc1a82558"),
                            DescTitle = "تروکار چیست؟",
                            Description = "تروکار ابزاری دقیق بوده و دسترسی به اجزای داخلی بدن را فراهم میکند.از این ابزار به عنوان یک واسطه استفاده می شود و معمولا شامل یک لوله توخالی با یک دسته می باشد.برخی از تروکارها انتهای هرم مانندی دارند و دو نوع تروکار صاف و انعطاف پذیر وجود دارد که  تیغه دار و یا بدون تیغه هستند.این نوع ها در بسیاری از تجهیزات پزشکی و در جراحی عمومی ، قلب و عروق ، اندروسکپی ،ارتوپدی و چشم استفاده می شود.از تروکارها معمولا برای دسترسی یک نقطه از بدن استفاده می شود علاوه بر دستگاه ها در بسیاری از تکنیکهای مدیریتی نیز استفاده می شود.برای تروکارها لازم است که لبه های تیزو ویژگی های دیگری برای مطلوب بودن را داشته باشند.تروکار ابزاری می باشد که انتهای آن به شکل هرم می باشد و برای دسترسی به رگ ها و حفرات استخوانی بدن استفاده می شود.در وهله اول باید لوله تروکار وارد بدن ش.با توجه به اینکه قسمتی از آن خم می شود.برای نقطه مورد نظر تروکار باید در حالت یکسانی قرار گرفته باشد همچنین میتواند برش متخلخل مانند دیگر ابزار و تجهیزات پزشکی ایجاد کند.",
                            ProductID = new Guid("94e8c44c-b1e4-43b2-9748-c9ed815e597d")
                        },
                        new
                        {
                            Id = new Guid("a38e454d-8fec-475b-9495-15c0a9104bfe"),
                            DescTitle = "موارد استفاده",
                            Description = "هر عمل پزشکی که شامل برش بافت باشد یک عمل ظریف محسوب شده و نیازمند تجهیزات مناسب با عمکلرد های مطلوب می باشد و لازم است تحقیقات ابتکاری در این زمینه صورت بگیرد.نتیجه این می شود که کاندسی برای اطمینان خاطر مشتریان خود  ابزار های پزشکی با کیفیت بالا تولید کند.نحوه تیز کردن تروکار ها به نحوه استفاده از آنها نیز بستگی دارد.کاندسی خدمات پس از فروش نیز برای مشتریان خود ارائه می دهد البته این ابزار ها باید به خوبی نگهداری شده و همچنین از تماس با موارد دیگر خودداری شود زیرا منجر به افزایش سطح الکتروشمیایی می شود.تمام این موارد تکنیک های طراحی میباشد تا تروکارهایی با تیغه هایی با کیفیت عالی و همچنین سایر تجهیزات پزشکی قابل اطمینان ارائه شود.کاندسی برنده تندیس MDEA می باشد.به دلیل اینکه تروکارها اندازه و شکل های متفاوتی دارد فرایند سفارش از کاندسی برای همه مشتریان مطلوب می باشد.اینکه آیا تیغه صاف یا هرمی شکل می باشد؟ کاندسی سعی دارد تا نیاز های فردی مشتریان خود را بر طرف نماید و با استفاده از تکنیک های جدید تیغه هایی با کیفیت بالا و پوشش بهتر ارائه دهد.",
                            ProductID = new Guid("94e8c44c-b1e4-43b2-9748-c9ed815e597d")
                        },
                        new
                        {
                            Id = new Guid("04902d0a-aea1-4deb-9b79-f0005c111e03"),
                            DescTitle = "ویژگی",
                            Description = "دريچه ورودی و نقطه ورود مخروطی.................قسمتهای کدگذاری شده با رنگ، تجسم بهتری را ارائه می دهد...................ثبات بالا و کنترل نشت......................موجود در سايزهای 3، 5، 10، 12، 15 میلی متری...................موجود در دونوع داراى تيغه و بدون تيغه....................داراى كانولا",
                            ProductID = new Guid("94e8c44c-b1e4-43b2-9748-c9ed815e597d")
                        },
                        new
                        {
                            Id = new Guid("d232d501-c6e4-4e05-a317-225f4b3d6aa1"),
                            DescTitle = "ویژگی",
                            Description = "دريچه ورودی و نقطه ورود مخروطی.................قسمتهای کدگذاری شده با رنگ، تجسم بهتری را ارائه می دهد...................ثبات بالا و کنترل نشت......................موجود در سايزهای 3، 5، 10، 12، 15 میلی متری...................موجود در دونوع داراى تيغه و بدون تيغه....................داراى كانولا",
                            ProductID = new Guid("94e8c44c-b1e4-43b2-9748-c9ed815e597d")
                        });
                });

            modelBuilder.Entity("Entities.ProductImg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductImgs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("faf49452-c7a2-48b9-b9b7-40089dc95034"),
                            ImageUrl = "bvf-1653421286.jpg",
                            ProductID = new Guid("b21aef73-8ded-4cc3-9aad-adfbd150bed5")
                        },
                        new
                        {
                            Id = new Guid("8ee6b6e6-2a91-4261-8034-7294d4e0e496"),
                            ImageUrl = "bvf-1653421290.jpg",
                            ProductID = new Guid("b21aef73-8ded-4cc3-9aad-adfbd150bed5")
                        },
                        new
                        {
                            Id = new Guid("0a81d7a2-2879-47e9-8623-a2eca830cfda"),
                            ImageUrl = "bvf-1653421296.jpg",
                            ProductID = new Guid("b21aef73-8ded-4cc3-9aad-adfbd150bed5")
                        },
                        new
                        {
                            Id = new Guid("2a24312c-2f7f-46e7-8dbc-5dd25ea9e80b"),
                            ImageUrl = "bvf-1653421300.jpg",
                            ProductID = new Guid("b21aef73-8ded-4cc3-9aad-adfbd150bed5")
                        },
                        new
                        {
                            Id = new Guid("0ba38a7e-0ab5-4564-b94c-1a1a94e9e055"),
                            ImageUrl = "hmef-1653421361.jpg",
                            ProductID = new Guid("398b7e58-bbc3-456f-924e-074c264c4031")
                        },
                        new
                        {
                            Id = new Guid("3d21073d-a644-47d1-a555-600294fb8a77"),
                            ImageUrl = "hmef-1653421364.jpg",
                            ProductID = new Guid("398b7e58-bbc3-456f-924e-074c264c4031")
                        },
                        new
                        {
                            Id = new Guid("66920cd3-e31c-4921-9b95-080737513f7c"),
                            ImageUrl = "hmef-1653421372.jpg",
                            ProductID = new Guid("398b7e58-bbc3-456f-924e-074c264c4031")
                        },
                        new
                        {
                            Id = new Guid("c9c8184f-5d3b-4ad9-8185-e4207dafc5f9"),
                            ImageUrl = "hmef-1653421375.jpg",
                            ProductID = new Guid("398b7e58-bbc3-456f-924e-074c264c4031")
                        },
                        new
                        {
                            Id = new Guid("53dd0ceb-bf4b-4e7a-a851-5caab52c88da"),
                            ImageUrl = "spirometer-filter-1653421549.jpg",
                            ProductID = new Guid("91db0db1-30b6-4934-8ab6-9bccdb0d4b74")
                        },
                        new
                        {
                            Id = new Guid("ac9c368d-4103-4f55-97ec-e7c3380ea400"),
                            ImageUrl = "spirometer-filter-1653421552.jpg",
                            ProductID = new Guid("91db0db1-30b6-4934-8ab6-9bccdb0d4b74")
                        },
                        new
                        {
                            Id = new Guid("afd25fd4-da04-488f-9953-acd5a86600c5"),
                            ImageUrl = "external-nasal-splint-trapezium-1653421606.jpg",
                            ProductID = new Guid("96043472-1394-414a-859b-dbae2ee0b9ca")
                        },
                        new
                        {
                            Id = new Guid("f01e3030-ddda-4385-8aff-92923d5fafe1"),
                            ImageUrl = "external-nasal-splint-trapezium-1653421611.jpg",
                            ProductID = new Guid("96043472-1394-414a-859b-dbae2ee0b9ca")
                        },
                        new
                        {
                            Id = new Guid("5c29f685-15c9-400f-b2bc-4e4f949f189a"),
                            ImageUrl = "external-nasal-splint-trapezium-1653421617.jpg",
                            ProductID = new Guid("96043472-1394-414a-859b-dbae2ee0b9ca")
                        },
                        new
                        {
                            Id = new Guid("0f4ed60d-e34f-465d-9a6f-bb00b17a612f"),
                            ImageUrl = "external-nasal-splint-trapezium-1653421621.jpg",
                            ProductID = new Guid("96043472-1394-414a-859b-dbae2ee0b9ca")
                        },
                        new
                        {
                            Id = new Guid("67e97732-275a-4be3-8427-56561668981c"),
                            ImageUrl = "external-nasal-splint-butterfly-1653421639.jpg",
                            ProductID = new Guid("5bfa2312-a815-46e3-bb71-38c1d441d69b")
                        },
                        new
                        {
                            Id = new Guid("f794fdf1-7ce8-42b9-9d4c-0576352413ba"),
                            ImageUrl = "external-nasal-splint-butterfly-1653421643.jpg",
                            ProductID = new Guid("5bfa2312-a815-46e3-bb71-38c1d441d69b")
                        },
                        new
                        {
                            Id = new Guid("9254433b-2792-4bd6-bf36-9525da194a3a"),
                            ImageUrl = "external-nasal-splint-butterfly-1653421646.jpg",
                            ProductID = new Guid("5bfa2312-a815-46e3-bb71-38c1d441d69b")
                        },
                        new
                        {
                            Id = new Guid("ba007421-723e-46da-b2b2-5f23366cf4e5"),
                            ImageUrl = "external-nasal-splint-butterfly-1653421653.jpg",
                            ProductID = new Guid("5bfa2312-a815-46e3-bb71-38c1d441d69b")
                        },
                        new
                        {
                            Id = new Guid("d085994a-9852-4f0c-9aef-38a01eb42b1e"),
                            ImageUrl = "external-nasal-splint-butterfly-1653421656.jpg",
                            ProductID = new Guid("5bfa2312-a815-46e3-bb71-38c1d441d69b")
                        },
                        new
                        {
                            Id = new Guid("219368f0-e254-48f2-97ea-ee53e35cdbbe"),
                            ImageUrl = "internal-splint-1653421674.jpg",
                            ProductID = new Guid("cadaf485-37c8-43c1-a784-8a1486d4b0d4")
                        },
                        new
                        {
                            Id = new Guid("e7aa1c91-4dbe-40da-b350-0c668741f5bc"),
                            ImageUrl = "internal-splint-1653421676.jpg",
                            ProductID = new Guid("cadaf485-37c8-43c1-a784-8a1486d4b0d4")
                        },
                        new
                        {
                            Id = new Guid("8f481ab8-792f-432e-8950-1a4768595416"),
                            ImageUrl = "surgery-blade-1653421720.jpg",
                            ProductID = new Guid("7d4756e1-f334-45a2-9cf4-b02c8de398bf")
                        },
                        new
                        {
                            Id = new Guid("76c75634-0d35-458e-b216-6f4145ace8e3"),
                            ImageUrl = "pain-pomp-1653421737.jpg",
                            ProductID = new Guid("f2da3a12-5362-4c64-a5cc-3821a6f40502")
                        },
                        new
                        {
                            Id = new Guid("8f6a7ac4-5cf7-47c6-898f-cb1042c9a655"),
                            ImageUrl = "suture-1653421753.jpg",
                            ProductID = new Guid("9fbdbdfb-ebda-4c01-94b6-37df0b7f4233")
                        },
                        new
                        {
                            Id = new Guid("00b693b6-bd53-4850-869e-d5049bf02ee3"),
                            ImageUrl = "circular-stapler-1653732880.jpeg",
                            ProductID = new Guid("b380acf2-45d4-40cc-8413-2b0c38666e3b")
                        },
                        new
                        {
                            Id = new Guid("50b88702-60ef-457d-a543-6c4664c26d54"),
                            ImageUrl = "circular-stapler-1653732885.jpg",
                            ProductID = new Guid("b380acf2-45d4-40cc-8413-2b0c38666e3b")
                        },
                        new
                        {
                            Id = new Guid("977f6191-ec4b-4b99-b0b4-301b8ad76806"),
                            ImageUrl = "circular-stapler-1653732889.jpg",
                            ProductID = new Guid("b380acf2-45d4-40cc-8413-2b0c38666e3b")
                        },
                        new
                        {
                            Id = new Guid("c1997be8-5623-4c0e-921f-8d11e7eb86fa"),
                            ImageUrl = "circular-stapler-1653732893.jpg",
                            ProductID = new Guid("b380acf2-45d4-40cc-8413-2b0c38666e3b")
                        },
                        new
                        {
                            Id = new Guid("03b1c419-55ba-49b6-be2a-7cade4d979ef"),
                            ImageUrl = "circular-stapler-1653733017.jpg",
                            ProductID = new Guid("b380acf2-45d4-40cc-8413-2b0c38666e3b")
                        },
                        new
                        {
                            Id = new Guid("ccb84fb7-a581-442a-b375-2fc5d8a79698"),
                            ImageUrl = "circular-stapler-1653733024.jpeg",
                            ProductID = new Guid("b380acf2-45d4-40cc-8413-2b0c38666e3b")
                        },
                        new
                        {
                            Id = new Guid("c6b55a78-1c5a-40c1-8960-0e7c80765986"),
                            ImageUrl = "curved-stapler-1653733379.jpg",
                            ProductID = new Guid("fd955430-0230-4f1d-92f5-bcaded597262")
                        },
                        new
                        {
                            Id = new Guid("0861aea3-ebc9-48b9-95f2-5f799cbbe1b1"),
                            ImageUrl = "curved-stapler-1653733384.jpg",
                            ProductID = new Guid("fd955430-0230-4f1d-92f5-bcaded597262")
                        },
                        new
                        {
                            Id = new Guid("9206497e-bb54-4c62-856f-e910a2931c41"),
                            ImageUrl = "endo-bag-1653733620.png",
                            ProductID = new Guid("c4821c34-c92c-4a0f-a94b-bfd4ad6cfd8b")
                        },
                        new
                        {
                            Id = new Guid("1ce70249-70bc-4159-b03e-098d5e129801"),
                            ImageUrl = "endo-bag-1653733631.jpg",
                            ProductID = new Guid("c4821c34-c92c-4a0f-a94b-bfd4ad6cfd8b")
                        },
                        new
                        {
                            Id = new Guid("a50ca01b-dcf6-42a0-bafe-0363d3df3ac5"),
                            ImageUrl = "endo-bag-1653733638.png",
                            ProductID = new Guid("c4821c34-c92c-4a0f-a94b-bfd4ad6cfd8b")
                        },
                        new
                        {
                            Id = new Guid("2b27dfbc-c5bb-4edd-9832-47cd06b87efb"),
                            ImageUrl = "endo-bag-1653733651.jpg",
                            ProductID = new Guid("c4821c34-c92c-4a0f-a94b-bfd4ad6cfd8b")
                        },
                        new
                        {
                            Id = new Guid("a3a11f3a-2b2c-4033-ae14-ec834f6b231d"),
                            ImageUrl = "endo-gi-realod-1653733766.jpg",
                            ProductID = new Guid("e88c63c0-b56f-4749-95c9-b6f081cf667c")
                        },
                        new
                        {
                            Id = new Guid("67272f73-f536-483a-8aa0-3c7c42859278"),
                            ImageUrl = "endo-gi-realod-1653733774.jpg",
                            ProductID = new Guid("e88c63c0-b56f-4749-95c9-b6f081cf667c")
                        },
                        new
                        {
                            Id = new Guid("1e78a537-4149-490d-b5ae-781c9bb409d0"),
                            ImageUrl = "endo-gi-realod-1653733880.jpg",
                            ProductID = new Guid("e88c63c0-b56f-4749-95c9-b6f081cf667c")
                        },
                        new
                        {
                            Id = new Guid("aa93b6d2-8658-4be6-b3bf-9d4e13c1c63b"),
                            ImageUrl = "endo-gi-stapler-1653734093.jpg",
                            ProductID = new Guid("58c1f884-560a-4433-8467-6df7d7779aa8")
                        },
                        new
                        {
                            Id = new Guid("7c305356-a80c-41a6-9ab5-f74c255c115d"),
                            ImageUrl = "endo-gi-stapler-1653734094.jpg",
                            ProductID = new Guid("58c1f884-560a-4433-8467-6df7d7779aa8")
                        },
                        new
                        {
                            Id = new Guid("7911ae9b-bec5-4acf-abf9-34b7f548194e"),
                            ImageUrl = "endo-gi-stapler-1653734098.jpg",
                            ProductID = new Guid("58c1f884-560a-4433-8467-6df7d7779aa8")
                        },
                        new
                        {
                            Id = new Guid("0033e218-9da6-4efb-b337-1803d8fce3f4"),
                            ImageUrl = "endo-gi-stapler-1653734103.jpg",
                            ProductID = new Guid("58c1f884-560a-4433-8467-6df7d7779aa8")
                        },
                        new
                        {
                            Id = new Guid("d09a56ad-7e99-4a29-9f87-68002394bdf1"),
                            ImageUrl = "eschelon-realod-1653734254.jpg",
                            ProductID = new Guid("fc72c813-10b4-42f6-a828-9e2b4c6723e4")
                        },
                        new
                        {
                            Id = new Guid("ef69c625-b713-448d-84c0-656b1dc09895"),
                            ImageUrl = "eschelon-realod-1653734257.jpg",
                            ProductID = new Guid("fc72c813-10b4-42f6-a828-9e2b4c6723e4")
                        },
                        new
                        {
                            Id = new Guid("04f931fe-c945-4314-a41a-8bc58c570bb4"),
                            ImageUrl = "eschelon-realod-1653734259.jpg",
                            ProductID = new Guid("fc72c813-10b4-42f6-a828-9e2b4c6723e4")
                        },
                        new
                        {
                            Id = new Guid("6d3d5a60-a222-461f-9dea-562447898110"),
                            ImageUrl = "eschelon-realod-1653734262.jpg",
                            ProductID = new Guid("fc72c813-10b4-42f6-a828-9e2b4c6723e4")
                        },
                        new
                        {
                            Id = new Guid("843e2279-579f-42de-ab13-f512042f59dd"),
                            ImageUrl = "eschelon-realod-1653734267.jpg",
                            ProductID = new Guid("fc72c813-10b4-42f6-a828-9e2b4c6723e4")
                        },
                        new
                        {
                            Id = new Guid("1df582b9-500d-4392-b952-487d30163581"),
                            ImageUrl = "eschelon-realod-1653734271.jpg",
                            ProductID = new Guid("fc72c813-10b4-42f6-a828-9e2b4c6723e4")
                        },
                        new
                        {
                            Id = new Guid("7fc93f14-2ab4-4341-a376-5f29bd5157d5"),
                            ImageUrl = "eschelon-stapler-1653734315.jpg",
                            ProductID = new Guid("6488e50c-b8a0-4af8-9d65-71366156b106")
                        },
                        new
                        {
                            Id = new Guid("94ff1440-7741-467c-b4da-87ed2486de4f"),
                            ImageUrl = "eschelon-stapler-1653734318.jpg",
                            ProductID = new Guid("6488e50c-b8a0-4af8-9d65-71366156b106")
                        },
                        new
                        {
                            Id = new Guid("1b0acfb1-8f36-4bd5-8709-3805a1a658f8"),
                            ImageUrl = "eschelon-stapler-1653734322.jpg",
                            ProductID = new Guid("6488e50c-b8a0-4af8-9d65-71366156b106")
                        },
                        new
                        {
                            Id = new Guid("ae27b7ab-e5ab-4bfc-b4ff-d00c216a04e6"),
                            ImageUrl = "hemolock-clips-1653734530.jpg",
                            ProductID = new Guid("59ec2c5b-e639-40da-b7b8-95a6d31f2d6d")
                        },
                        new
                        {
                            Id = new Guid("a5a5678f-ac82-4e6d-bcd0-fe63a7d90b66"),
                            ImageUrl = "hemolock-clips-1653734533.jpg",
                            ProductID = new Guid("59ec2c5b-e639-40da-b7b8-95a6d31f2d6d")
                        },
                        new
                        {
                            Id = new Guid("5ad7b6d1-5293-4d0a-8c18-4fde79f6d5a4"),
                            ImageUrl = "hemolock-clips-1653734536.jpg",
                            ProductID = new Guid("59ec2c5b-e639-40da-b7b8-95a6d31f2d6d")
                        },
                        new
                        {
                            Id = new Guid("b1b79a26-d863-4dfe-848a-024f4be2ef51"),
                            ImageUrl = "hemolock-clips-1653734539.jpg",
                            ProductID = new Guid("59ec2c5b-e639-40da-b7b8-95a6d31f2d6d")
                        },
                        new
                        {
                            Id = new Guid("02fbb108-c7db-439c-a2de-82134b5ea52d"),
                            ImageUrl = "ligasure-laparascopic-1653734575.jpg",
                            ProductID = new Guid("dd713b1e-379b-43d3-a59e-571c6230ff86")
                        },
                        new
                        {
                            Id = new Guid("9ae251c8-822f-43a9-b8bb-608fad5b93ed"),
                            ImageUrl = "ligasure-laparascopic-1653734666.jpg",
                            ProductID = new Guid("dd713b1e-379b-43d3-a59e-571c6230ff86")
                        },
                        new
                        {
                            Id = new Guid("f97d5f48-bb63-406a-bfbe-05f769ed6ba6"),
                            ImageUrl = "ligasure-laparascopic-1653734668.jpg",
                            ProductID = new Guid("dd713b1e-379b-43d3-a59e-571c6230ff86")
                        },
                        new
                        {
                            Id = new Guid("0f25ca84-ae4b-4aa7-ac01-62447d690684"),
                            ImageUrl = "linear-cutter-stapler-1653734707.jpg",
                            ProductID = new Guid("106f346e-b5e9-4117-b6e1-eb0273a65889")
                        },
                        new
                        {
                            Id = new Guid("612ac1c8-9fef-408c-9850-6ecabe8e343b"),
                            ImageUrl = "linear-cutter-stapler-1653734709.jpg",
                            ProductID = new Guid("106f346e-b5e9-4117-b6e1-eb0273a65889")
                        },
                        new
                        {
                            Id = new Guid("2dc3a86d-cc09-436a-858b-cca7ba6384ee"),
                            ImageUrl = "linear-cutter-stapler-1653734712.jpg",
                            ProductID = new Guid("106f346e-b5e9-4117-b6e1-eb0273a65889")
                        },
                        new
                        {
                            Id = new Guid("dad86a01-0967-4f85-befe-d6b8d5b07fb0"),
                            ImageUrl = "linear-cutter-stapler-1653734715.jpg",
                            ProductID = new Guid("106f346e-b5e9-4117-b6e1-eb0273a65889")
                        },
                        new
                        {
                            Id = new Guid("bccb22e6-508f-4837-aec9-712876f6aa47"),
                            ImageUrl = "linear-cutter-stapler-1653734721.jpg",
                            ProductID = new Guid("106f346e-b5e9-4117-b6e1-eb0273a65889")
                        },
                        new
                        {
                            Id = new Guid("96895f47-0c27-444d-bb97-5007b1eebdcb"),
                            ImageUrl = "linear-cutter-stapler-1653734727.jpg",
                            ProductID = new Guid("106f346e-b5e9-4117-b6e1-eb0273a65889")
                        },
                        new
                        {
                            Id = new Guid("0fda1370-f462-4635-ad2a-9a588bd2d997"),
                            ImageUrl = "pph-stapler-1653734831.jpg",
                            ProductID = new Guid("01756d04-f7c1-4815-ab5c-0555d9c62b35")
                        },
                        new
                        {
                            Id = new Guid("047cb219-f379-4793-8537-0c9941304933"),
                            ImageUrl = "pph-stapler-1653734833.jpg",
                            ProductID = new Guid("01756d04-f7c1-4815-ab5c-0555d9c62b35")
                        },
                        new
                        {
                            Id = new Guid("c33d54ef-98ed-40ff-8440-1fc9062565fe"),
                            ImageUrl = "pph-stapler-1653734836.jpg",
                            ProductID = new Guid("01756d04-f7c1-4815-ab5c-0555d9c62b35")
                        },
                        new
                        {
                            Id = new Guid("a182c68c-c53d-4007-94ca-607d786c01b1"),
                            ImageUrl = "pph-stapler-1653734840.jpg",
                            ProductID = new Guid("01756d04-f7c1-4815-ab5c-0555d9c62b35")
                        },
                        new
                        {
                            Id = new Guid("172def63-51ec-4d8c-ad88-78cb6c2c4995"),
                            ImageUrl = "pph-stapler-1653734842.jpg",
                            ProductID = new Guid("01756d04-f7c1-4815-ab5c-0555d9c62b35")
                        },
                        new
                        {
                            Id = new Guid("8878d952-9cd2-423b-be97-7d3eaefc6f44"),
                            ImageUrl = "pph-stapler-1653734844.jpg",
                            ProductID = new Guid("01756d04-f7c1-4815-ab5c-0555d9c62b35")
                        },
                        new
                        {
                            Id = new Guid("de261b75-5b31-4617-b78b-1c9ffcab58ac"),
                            ImageUrl = "skin-stapler-1653734873.jpg",
                            ProductID = new Guid("4ae1d802-87e4-40fe-b148-c624e8520bb1")
                        },
                        new
                        {
                            Id = new Guid("f91c8257-31e5-46ea-bc0c-6c1a217827ed"),
                            ImageUrl = "skin-stapler-1653734875.jpg",
                            ProductID = new Guid("4ae1d802-87e4-40fe-b148-c624e8520bb1")
                        },
                        new
                        {
                            Id = new Guid("ebe196dd-180f-4b76-a6f0-4e066aa3a65b"),
                            ImageUrl = "skin-stapler-1653734879.jpg",
                            ProductID = new Guid("4ae1d802-87e4-40fe-b148-c624e8520bb1")
                        },
                        new
                        {
                            Id = new Guid("583e06de-a0db-4fb7-a630-a5b5cfe601bc"),
                            ImageUrl = "trocar-1653734912.jpg",
                            ProductID = new Guid("94e8c44c-b1e4-43b2-9748-c9ed815e597d")
                        },
                        new
                        {
                            Id = new Guid("e50680bf-ca03-4d62-abc6-c2bb8f9219e2"),
                            ImageUrl = "trocar-1653735053.jpg",
                            ProductID = new Guid("94e8c44c-b1e4-43b2-9748-c9ed815e597d")
                        },
                        new
                        {
                            Id = new Guid("5cd8293b-78ea-42af-bc52-9cc864d1cb8a"),
                            ImageUrl = "trocar-1653735056.jpg",
                            ProductID = new Guid("94e8c44c-b1e4-43b2-9748-c9ed815e597d")
                        });
                });

            modelBuilder.Entity("Entities.ProductProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PropertyDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductProperties", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9a7101d-b74f-4039-ba39-9fdff2f06b3c"),
                            ProductID = new Guid("fd955430-0230-4f1d-92f5-bcaded597262"),
                            PropertyDetail = "	\r\nManual",
                            PropertyTitle = "Power Source"
                        },
                        new
                        {
                            Id = new Guid("f27635fe-00dc-48b1-a3d0-896c1e135c3c"),
                            ProductID = new Guid("fd955430-0230-4f1d-92f5-bcaded597262"),
                            PropertyDetail = "1 year",
                            PropertyTitle = "Warranty"
                        },
                        new
                        {
                            Id = new Guid("c9ffb435-adf0-4918-816a-11838faab359"),
                            ProductID = new Guid("fd955430-0230-4f1d-92f5-bcaded597262"),
                            PropertyDetail = "After-sale Service",
                            PropertyTitle = "Online technical support"
                        },
                        new
                        {
                            Id = new Guid("f72a4f57-9906-4411-89aa-c1b1f12b899c"),
                            ProductID = new Guid("fd955430-0230-4f1d-92f5-bcaded597262"),
                            PropertyDetail = "Metal, Plastic",
                            PropertyTitle = "Material"
                        },
                        new
                        {
                            Id = new Guid("007fb7d2-d185-43e2-9550-92f286130c66"),
                            ProductID = new Guid("fd955430-0230-4f1d-92f5-bcaded597262"),
                            PropertyDetail = "1years",
                            PropertyTitle = "Shelf Life"
                        },
                        new
                        {
                            Id = new Guid("bc9f0a10-48f4-4368-b746-77bef0bbe639"),
                            ProductID = new Guid("fd955430-0230-4f1d-92f5-bcaded597262"),
                            PropertyDetail = "ce",
                            PropertyTitle = "Quality Certification"
                        },
                        new
                        {
                            Id = new Guid("dc5485c0-56cd-495d-afa4-803f6cba7095"),
                            ProductID = new Guid("fd955430-0230-4f1d-92f5-bcaded597262"),
                            PropertyDetail = "Class II",
                            PropertyTitle = "Instrument classification"
                        },
                        new
                        {
                            Id = new Guid("bf0316c2-1399-444e-9ea2-0a3266555e5c"),
                            ProductID = new Guid("fd955430-0230-4f1d-92f5-bcaded597262"),
                            PropertyDetail = "GB-T13810-2007",
                            PropertyTitle = "Safety standard"
                        },
                        new
                        {
                            Id = new Guid("eb892233-9254-4ec9-89a9-30ce26f2697f"),
                            ProductID = new Guid("fd955430-0230-4f1d-92f5-bcaded597262"),
                            PropertyDetail = "30-45",
                            PropertyTitle = "Size"
                        },
                        new
                        {
                            Id = new Guid("5b38d048-fa29-44de-a0f7-4835cec071a3"),
                            ProductID = new Guid("fd955430-0230-4f1d-92f5-bcaded597262"),
                            PropertyDetail = "Abdominal Surgery Equipments",
                            PropertyTitle = "Properties"
                        },
                        new
                        {
                            Id = new Guid("c6284284-85bb-40d4-ae9d-2b85dcec96a0"),
                            ProductID = new Guid("fd955430-0230-4f1d-92f5-bcaded597262"),
                            PropertyDetail = "Knife",
                            PropertyTitle = "Type"
                        },
                        new
                        {
                            Id = new Guid("732476d3-044b-4a13-baac-7cdce5eed624"),
                            ProductID = new Guid("fd955430-0230-4f1d-92f5-bcaded597262"),
                            PropertyDetail = "Titanium,ABS.PE.PA,Stainless Stell Etc",
                            PropertyTitle = "Material"
                        },
                        new
                        {
                            Id = new Guid("4b21ee4c-6478-4597-b147-37047b2f5bfc"),
                            ProductID = new Guid("b21aef73-8ded-4cc3-9aad-adfbd150bed5"),
                            PropertyDetail = "حاوی فیلترهای ویروسی باکتریایی با راندمان فیلتراسیون ۹۹.۹۹۹٪"
                        },
                        new
                        {
                            Id = new Guid("615fdcfc-423c-45b3-9d13-d55b9d4eb057"),
                            ProductID = new Guid("b21aef73-8ded-4cc3-9aad-adfbd150bed5"),
                            PropertyDetail = "دارای اتصالات مخروطی مطابق با استانداردهای ISO برای اطمینان از ثبات اتصال"
                        },
                        new
                        {
                            Id = new Guid("d89d68cc-9fff-4eb0-917c-784d20b29b72"),
                            ProductID = new Guid("b21aef73-8ded-4cc3-9aad-adfbd150bed5"),
                            PropertyDetail = "استریل شده و قابلیت استفاده برای تنفس اطفال و بزرگسال"
                        },
                        new
                        {
                            Id = new Guid("c43861e9-29c6-4358-a4d5-ca8b8769bc42"),
                            ProductID = new Guid("b21aef73-8ded-4cc3-9aad-adfbd150bed5"),
                            PropertyDetail = "دارای قابلیت جذب و نگهداری رطوبت و گرما در هوای ورودی"
                        },
                        new
                        {
                            Id = new Guid("6cfa7038-3c19-4941-ba86-864fb7f70bc6"),
                            ProductID = new Guid("b21aef73-8ded-4cc3-9aad-adfbd150bed5"),
                            PropertyDetail = "دارای مکانیزم منع انتقال آلودگی از دستگاه به بیمار و از بیمار به دستگاه"
                        });
                });

            modelBuilder.Entity("Entities.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeNameEN")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TypeNameFr")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("15f8dfc3-5c88-4a9e-be20-3ac476192583"),
                            TypeNameEN = "Laparascopy",
                            TypeNameFr = "محصولات لاپاراسکوپی"
                        },
                        new
                        {
                            Id = new Guid("f464f47b-664f-476e-8d31-372b5cc6d488"),
                            TypeNameEN = "ENT",
                            TypeNameFr = "محصولات ENT"
                        },
                        new
                        {
                            Id = new Guid("65d34326-ce95-474e-96f7-850a6154fefb"),
                            TypeNameEN = "respiratory-anesthesia",
                            TypeNameFr = "محصولات بیهوشی تنفسی"
                        },
                        new
                        {
                            Id = new Guid("e1b3d3c4-4b0b-4d86-a943-2cacc55ce7d2"),
                            TypeNameEN = "surgery",
                            TypeNameFr = "محصولات جراحی"
                        });
                });

            modelBuilder.Entity("Entities.Product", b =>
                {
                    b.HasOne("Entities.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Entities.ProductDesc", b =>
                {
                    b.HasOne("Entities.Product", "Product")
                        .WithMany("ProductDescriptions")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.ProductImg", b =>
                {
                    b.HasOne("Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.ProductProperty", b =>
                {
                    b.HasOne("Entities.Product", "Product")
                        .WithMany("ProductProperties")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Product", b =>
                {
                    b.Navigation("ProductDescriptions");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductProperties");
                });

            modelBuilder.Entity("Entities.ProductType", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
